### ISSUE TITLE
[CONTRIB-8097] Enforce coding guidelines for trailing comma in multi-line array declaration

### ISSUE THREAD

**Issue by sarjona** [moodlehq/moodle-cs#25]
This is about to enforce the following policy decided recently (https://tracker.moodle.org/browse/MDLSITE-5873).

> Policy: Trailing comma in multi-line array declaration
> Since 20th May 2020, this rule applies:
> 
> 1. The uses of a trailing comma on multi-line array declaration is required in PHP and JS.
> 2. It's NOT required to change all current old-style occurrences in the codebase. We'll follow a progressive approach here (new code and modified code)
> For example for the expected format:
> 
> $foo = [
>     'a',
>     'b',
>     'c',
> ];
>

This issue is about to verify these details in the codechecker. Nothing more, nothing less.

---
Reporter: Sara Arjona
Original issue: https://tracker.moodle.org/browse/CONTRIB-8097

**Comment by andrewnicols** [comment]
MediaWiki have a rule we can use:

https://packagist.org/packages/mediawiki/mediawiki-codesniffer

```
+    <rule ref="MediaWiki.Arrays.TrailingComma">
+      <properties>
+        <property name="singleLine" value="false" />
+        <property name="multiLine" value="true" />
+      </properties>
+    </rule>
```

**Comment by jrchamp** [comment]
https://github.com/PHPCSStandards/PHPCSExtra has a significant number of sniffs, including one for this: NormalizedArrays.Arrays.CommaAfterLast

**Comment by stronk7** [comment]
While I'm not a fan of adding too many standards from outside (as commented in #34), the [PHPCSExtra](https://github.com/PHPCSStandards/PHPCSExtra) is really interesting, specifically the `Universal` rules, easy to add to our ruleset, but also because it comes from Juliette, also super involved in the PHPCompatibility one, also the composer plugin that we use to install it and other things...so somebody to trust, I'd say.

Also, somehow related... I've been thinking about #45 and, maybe, the way to go is something similar to the schema used by `PHPCSExtra`, offering different rulesets (standards) and allow people to adhere to them (say current "moodle", the general one, then a "moodle-strict" or a "moodle-crazy/next" or so...).

Ciao :-)

**Comment by andrewnicols** [comment]
I'ma big fan of that approach. I have a local schema `moodle-strict` which does some of this but I'd prefer someting in core.

**Comment by stronk7** [comment]
BTW,

unless I'm wrong... the `Squiz.Arrays.ArrayDeclaration` sniff already include abilities to check for trailing commas (and many other things like spaces before commas, before and after brackets...).

Maybe we can add it to our ruleset with other, opinionated, checks disabled and see how the trailing commas one goes... just overlooking it seems that makes a difference between single-line and multi-line declarations, exactly like we want.

Ciao :-)
