### ISSUE TITLE
GPL copyright statement at the top check not properly checked

### ISSUE THREAD

**Issue by keevan** [moodlehq/moodle-cs#28]
https://docs.moodle.org/dev/Coding_style#Files

This is in reference to the line below, normally referenced as such:
```
// This file is part of Moodle - http://moodle.org/
```

Given this example:
```
// This file is part of my dinner
```

**Expectations**:  should fail, with some message about the proposed/expected format - could do additional checks if the output is different.

**Actual:** passes just fine.

**Comment by stronk7** [comment]
Hi,

yeah. I'm going to close this as won't fix. I remember when that Sniff was created and agreed about leaving that line "free", because organisations out there (partners, univs, ...) may use it with some freedom. Of course, offending/wrong ("my dinner", heheh), shouldn't be used, but that's away from the Sniff purpose.

Thanks for the reports and sorry for the late response, ciao :-)
