### ISSUE TITLE
Class MoodleHQ\MoodleCS\moodle\Tests\MoodleCsStandardTest does not comply with psr-4 autoloading standard.

### ISSUE THREAD

**Issue by ewallah** [moodlehq/moodle-cs#55]
Message shown when using GitHub actions ([sample](https://github.com/ewallah/moodle-availability_coursecompleted/actions/runs/6048684201/job/16414800182#step:6:8985))

I do not know if this is related, but now all my GitHub actions [scripts fail](https://github.com/ewallah/moodle-enrol_coursecompleted/actions/runs/6015781723) because composer cannot install dependencies from lock file.

**Comment by stronk7** [comment]
Thanks for reporting this, @ewallah . Yeah, I had already noticed it but keep not looking coz it doesn't seem to break anything.

Regarding the recent composer problems, while still triple-checking all our composer.json files and inter-dependencies, I've reported it upstream, @ https://github.com/composer/composer/issues/11613 because, for sure, the problem has started to happen (to us) with composer 2.6.0 and 2.6.1, released few hours ago.

I'll take a look to this issue soon...ciao :-)
